[[chapter2]]
== Load/Store pair instructions

The Zilsp extension provides load/store pair instructions for RV32 analogous to the existing RV64 doubleword load/store instructions. The existing RV64 encodings are reused, which are reserved in RV32 without this extension.

Operands containing `src` for store instructions and `dest` for load instructions are held in aligned `x`-register pairs, i.e., register numbers must be even. Use of misaligned (odd-numbered) registers for these operands is _reserved_.

Regardless of endianness, the lower-numbered register holds the
low-order bits, and the higher-numbered register holds the high-order
bits: e.g., bits 31:0 of an operand in Zilsp might be held in register `x14`, with bits 63:32 of that operand held in `x15`.

The Zilsp extension adds the following RV32-only instructions:

  - LD loads a 64-bit value into registers `rd` and `rd+1`
  - SD stores a 64-bit value from registers `rs2` and `rs2+1`

[NOTE]
====
Implementations may need to crack these instructions, and perform to memory operations in sequence. Therefore, implementations are not required to ensure atomicity in loading/storing to/from the individual registers relating to a 64-bit operand.
====

=== Compressed Load/Store pair instructions

If the C extension is present, Zilsp adds the following RV32-only instructions:

  - C.LDSP loads stack-pointer relative 64-bit value into registers `rd'` and `rd'+1`. It computes its effective address by adding the zero-extended offset, scaled by 8, to the stack pointer, `x2`. It expands to `ld rd, offset(x2)`. C.LDSP is only valid when _rd_&#x2260;x0; the code points with _rd_=x0 are reserved.
  - C.SDSP stores a stack-pointer relative 64-bit value from registers `rs2'` and `rs2'+1`. It computes an effective address by adding the _zero_-extended offset, scaled by 8, to the stack pointer, `x2`. It expands to `sd rs2, offset(x2)`.
  - C.LD loads a 64-bit value into registers `rd'` and `rd'+1`. It expands to
  `ld rd', offset(rs1')`.
  - C.SD stores a 64-bit value from registers `rs2'` and `rs2'+1`. It expands to
  `sd rs2', offset(rs1')`.


=== Use of x0 as operand

LD and C.LD instructions with destination `x0` are processed as any other load, but the result is discarded entirely. Specifically, a load pair to `x0` does not cause `x1` to be written. For C.LDSP, usage of `x0` as the destination is reserved.

When using `x0` as `src` of SD, C.SD, or C.SDSP, the entire 64-bit operand is zero — i.e., register `x1` is not accessed.