
== Load/Store pair

The Zilsd & Zcmlsd extensions provide load/store pair instructions for RV32 analogous to RV64 doubleword load/store instructions, reusing the existing RV64 encodings.

Operands containing `src` for store instructions and `dest` for load instructions are held in aligned `x`-register pairs, i.e., register numbers must be even. Use of misaligned (odd-numbered) registers for these operands is _reserved_.

Regardless of endianness, the lower-numbered register holds the
low-order bits, and the higher-numbered register holds the high-order
bits: e.g., bits 31:0 of an operand in Zilsd might be held in register `x14`, with bits 63:32 of that operand held in `x15`.

[[zilsd, Zilsd]]
=== Load/Store pair instructions (Zilsd)

The Zilsd extension adds the following RV32-only instructions:

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|yes
|no
|ld rd, simm(rs1)
|<<#insns-ld>>

|yes
|no
|sd rs2, simm(rs1)
|<<#insns-sd>>

|===

[NOTE]
====
As the access size is 64-bit, accesses are only considered naturally aligned for effective addresses that are a multiple of 8. In this case, these instruction are guaranteed to not raise an address-misaligned exception.
====

[NOTE]
====
Implementations may need to crack these instructions, and perform two memory operations in sequence. Therefore, implementations are not required to ensure atomicity when storing to memory. However, writing to both registers written by a 64-bit load must happen atomically to ensure fault handling is possible.
====

[[zcmlsd, Zcmlsd]]
=== Compressed Load/Store pair instructions (Zcmlsd)

Zcmlsd depends on Zilsd and Zca. It has overlapping encodings with Zcf and is thus incompatible with Zcf.

Zcmlsd adds the following RV32-only instructions:

[%header,cols="^1,^1,4,8"]
|===
|RV32
|RV64
|Mnemonic
|Instruction

|yes
|no
|c.ldsp rd, uimm(sp)
|<<#insns-cldsp>>

|yes
|no
|c.sdsp rs2, uimm(sp)
|<<#insns-csdsp>>

|yes
|no
|c.ld rd', uimm(rs1')
|<<#insns-cld>>

|yes
|no
|c.sd rs2', uimm(rs1')
|<<#insns-csd>>

|===

=== Use of x0 as operand

LD instructions with destination `x0` are processed as any other load, but the result is discarded entirely. Specifically, a load pair to `x0` does not cause `x1` to be written. For C.LDSP, usage of `x0` as the destination is reserved.

When using `x0` as `src` of SD or C.SDSP, the entire 64-bit operand is zero — i.e., register `x1` is not accessed.

=== Fault Handling

In implementations that crack Zilsd instructions for sequential execution, correct execution requires addressing idempotent memory, because the hart must be able to handle traps detected during the sequence. The entire sequence is re-executed after returning from the trap handler, and multiple traps are possible during the sequence.

[NOTE]
====
It is implementation defined whether interrupts can also be taken during the sequence execution.
====

=== Software view of the load/store pair sequence

From a software perspective the load/store pair instructions appears as:

* load instructions:
** A sequence of one or more loads reading the bytes of the double word without updating rd or rd+1
*** The bytes may be loaded in any order.
*** The bytes may be grouped into larger accesses.
*** Any of the bytes may be loaded multiple times.
** An atomic write of the load result into rd and rd+1
* store instructions:
** A sequence of one or more stores writing the bytes of the double word
*** The bytes may be stored in any order.
*** The bytes may be grouped into larger accesses.
*** Any of the bytes may be stored multiple times.

=== Non-idempotent memory handling

An implementation may have a requirement to issue a load/store pair instruction to non-idempotent memory.

If an implementation of a hart does not support Zilsd instructions to non-idempotent memories, the hart may use an idempotency PMA to detect it and take a load or store access fault exception in order to avoid unpredictable results.

Software should only use these instructions on non-idempotent memory regions when software can tolerate the required memory accesses being issued repeatedly in the case that they cause exceptions.

<<<

=== Instructions
[#insns-ld,reftext="Load doubleword to register pair, 32-bit encoding"]
==== ld

Synopsis::
Load doubleword to even/odd register pair, 32-bit encoding

Mnemonic::
ld rd, simm(rs1)

Encoding (RV32)::
[wavedrom, ,svg]
....
{reg: [
  {bits: 7,  name: 0x3,    attr: ['LOAD'], type: 8},
  {bits: 5,  name: 'rd', attr: ['dest, dest[0]=0'], type: 2},
  {bits: 3,  name: 0x3, attr: ['width=D'], type: 8},
  {bits: 5,  name: 'rs1', attr: ['base'], type: 4},
  {bits: 12, name: 'imm[11:0]', attr: ['offset[11:0]'], type: 3},
]}
....

Description:: 
Loads a 64-bit value into registers `rd` and `rd+1`.
The effective address is obtained by adding register rs1 to the
sign-extended 12-bit offset.

Included in: <<zilsd>>

<<<

[#insns-sd,reftext="Store doubleword from register pair, 32-bit encoding"]
==== sd

Synopsis::
Store doubleword from even/odd register pair, 32-bit encoding

Mnemonic::
sd rs2, simm(rs1)

Encoding (RV32)::
[wavedrom, ,svg]
....
{reg: [
  {bits: 7,  name: 0x23,   attr: ['STORE'], type: 8},
  {bits: 5,  name: 'imm[4:0]', attr: ['offset[4:0]'], type: 3},
  {bits: 3,  name: 0x3, attr: ['width=D'], type: 8},
  {bits: 5,  name: 'rs1', attr: ['base'], type: 4},
  {bits: 5,  name: 'rs2', attr: ['src, src[0]=0'], type: 4},
  {bits: 7,  name: 'imm[11:5]', attr: ['offset[11:5]'], type: 3},
]}
....

Description:: 
Stores a 64-bit value from registers `rs2` and `rs2+1`.
The effective address is obtained by adding register rs1 to the
sign-extended 12-bit offset.

Included in: <<zilsd>>

<<<

[#insns-cldsp,reftext="Stack-pointer based load doubleword to register pair, 16-bit encoding"]
==== c.ldsp

Synopsis::
Stack-pointer based load doubleword to even/odd register pair, 16-bit encoding

Mnemonic::
c.ldsp rd, uimm(sp)

Encoding (RV32)::
[wavedrom, ,svg]
....
{reg: [
  {bits: 2, name: 0x2,      type: 8, attr: ['C2']},
  {bits: 5, name: 'imm',    type: 3, attr: ['offset[4:3|8:6]']},
  {bits: 5, name: 'rd',     type: 2, attr: ['dest≠0, dest[0]=0']},
  {bits: 1, name: 'imm',    type: 3, attr: ['offset[5]']},
  {bits: 3, name: 0x3,      type: 8, attr: ['C.LDSP']},
], config: {bits: 16}}
....

Description:: 
Loads stack-pointer relative 64-bit value into registers `rd'` and `rd'+1`. It computes its effective address by adding the zero-extended offset, scaled by 8, to the stack pointer, `x2`. It expands to `ld rd, offset(x2)`. C.LDSP is only valid when _rd_&#x2260;x0; the code points with _rd_=x0 are reserved.

Included in: <<zcmlsd>>

<<<

[#insns-csdsp,reftext="Stack-pointer based store doubleword from register pair, 16-bit encoding"]
==== c.sdsp

Synopsis::
Stack-pointer based store doubleword from even/odd register pair, 16-bit encoding

Mnemonic::
c.sdsp rs2, uimm(sp)

Encoding (RV32)::
[wavedrom, ,svg]
....
{reg: [
  {bits: 2, name: 0x2,      type: 8, attr: ['C2']},
  {bits: 5, name: 'rs2',    type: 4, attr: ['src, src[0]=0']},
  {bits: 6, name: 'imm',    type: 3, attr: ['offset[5:3|8:6]']},
  {bits: 3, name: 0x7,      type: 8, attr: ['C.SDSP']},
], config: {bits: 16}}
....

Description:: 
Stores a stack-pointer relative 64-bit value from registers `rs2'` and `rs2'+1`. It computes an effective address by adding the _zero_-extended offset, scaled by 8, to the stack pointer, `x2`. It expands to `sd rs2, offset(x2)`.

Included in: <<zcmlsd>>

<<<

[#insns-cld,reftext="Load doubleword to register pair, 16-bit encoding"]
==== c.ld

Synopsis::
Load doubleword to even/odd register pair, 16-bit encoding

Mnemonic::
c.ld rd', uimm(rs1')

Encoding (RV32)::
[wavedrom, ,svg]
....
{reg: [
  {bits: 2, name: 0x0,       type: 8, attr: ['C0']},
  {bits: 3, name: 'rd`',     type: 2, attr: ['dest, dest[0]=0']},
  {bits: 2, name: 'imm',     type: 3, attr: ['offset[7:6]']},
  {bits: 3, name: 'rs1`',    type: 4, attr: ['base']},
  {bits: 3, name: 'imm',     type: 3, attr: ['offset[5:3]']},
  {bits: 3, name: 0x3,       type: 8, attr: ['C.LD']},
], config: {bits: 16}}
....

Description:: 
Loads a 64-bit value into registers `rd'` and `rd'+1`.
It computes an effective address by adding the zero-extended offset, scaled by 8, to the base address in register rs1'.

Included in: <<zcmlsd>>

<<<

[#insns-csd,reftext="Store doubleword from register pair, 16-bit encoding"]
==== c.sd

Synopsis::
Store doubleword from even/odd register pair, 16-bit encoding

Mnemonic::
c.sd rs2', uimm(rs1')

Encoding (RV32)::
[wavedrom, ,svg]
....
{reg: [
  {bits: 2, name: 0x0,      type: 8, attr: ['C0']},
  {bits: 3, name: 'rs2`',   type: 4, attr: ['src, src[0]=0']},
  {bits: 2, name: 'imm',    type: 3, attr: ['offset[7:6]']},
  {bits: 3, name: 'rs1`',   type: 4, attr: ['base']},
  {bits: 3, name: 'imm',    type: 3, attr: ['offset[5:3]']},
  {bits: 3, name: 0x7,      type: 8, attr: ['C.SD']},
], config: {bits: 16}}
....

Description:: 
Stores a 64-bit value from registers `rs2'` and `rs2'+1`.
It computes an effective address by adding the zero-extended offset, scaled by 8, to the base address in register rs1'.
It expands to `sd rs2', offset(rs1')`.

Included in: <<zcmlsd>>