[[chapter2]]
== Load/Store pair instructions

The Zilsd extension provides load/store pair instructions for RV32 analogous to the existing RV64 doubleword load/store instructions. The existing RV64 encodings are reused, which are reserved in RV32 without this extension.

Operands containing `src` for store instructions and `dest` for load instructions are held in aligned `x`-register pairs, i.e., register numbers must be even. Use of misaligned (odd-numbered) registers for these operands is _reserved_.

Regardless of endianness, the lower-numbered register holds the
low-order bits, and the higher-numbered register holds the high-order
bits: e.g., bits 31:0 of an operand in Zilsd might be held in register `x14`, with bits 63:32 of that operand held in `x15`.

The Zilsd extension adds the following RV32-only instructions:

  - LD loads a 64-bit value into registers `rd` and `rd+1`
  - SD stores a 64-bit value from registers `rs2` and `rs2+1`

[NOTE]
====
Implementations may need to crack these instructions, and perform to memory operations in sequence. Therefore, implementations are not required to ensure atomicity in loading/storing to/from the individual registers relating to a 64-bit operand.
====

=== Compressed Load/Store pair instructions

If the C extension is present and F is not present, Zilsd adds the following RV32-only instructions:

  - C.LDSP loads stack-pointer relative 64-bit value into registers `rd'` and `rd'+1`. It computes its effective address by adding the zero-extended offset, scaled by 8, to the stack pointer, `x2`. It expands to `ld rd, offset(x2)`. C.LDSP is only valid when _rd_&#x2260;x0; the code points with _rd_=x0 are reserved.
  - C.SDSP stores a stack-pointer relative 64-bit value from registers `rs2'` and `rs2'+1`. It computes an effective address by adding the _zero_-extended offset, scaled by 8, to the stack pointer, `x2`. It expands to `sd rs2, offset(x2)`.
  - C.LD loads a 64-bit value into registers `rd'` and `rd'+1`.
  It computes an effective address by adding the zero-extended offset, scaled by 8, to the base address in register rs1'.
  It expands to `ld rd', offset(rs1')`.
  - C.SD stores a 64-bit value from registers `rs2'` and `rs2'+1`.
  It computes an effective address by adding the zero-extended offset, scaled by 8, to the base address in register rs1'.
  It expands to `sd rs2', offset(rs1')`.

These instructions are mutually exclusive with Zcf.

=== Use of x0 as operand

LD instructions with destination `x0` are processed as any other load, but the result is discarded entirely. Specifically, a load pair to `x0` does not cause `x1` to be written. For C.LDSP, usage of `x0` as the destination is reserved.

When using `x0` as `src` of SD or C.SDSP, the entire 64-bit operand is zero — i.e., register `x1` is not accessed.

=== Fault Handling

In implementations that crack Zilsd instructions for sequential execution, correct execution requires addressing idempotent memory, because the core must be able to handle traps detected during the sequence. The entire sequence is re-executed after returning from the trap handler, and multiple traps are possible during the sequence.

If a trap occurs during the sequence then xEPC is updated with the PC of the instruction, xTVAL (if not read-only-zero) updated with the bad address if it was an access fault and xCAUSE updated with the type of trap.

[NOTE]
====
It is implementation defined whether interrupts can also be taken during the sequence execution.
====

=== Software view of the load/store pair sequence

From a software perspective the load/store pair instructions appears as:

* load instructions:
** A sequence of one or more loads reading the bytes of the double word without updating rd or rd+1
*** The bytes may be loaded in any order.
*** The bytes may be grouped into larger accesses.
*** Any of the bytes may be loaded multiple times.
** An atomic write of the load result into rd and rd+1
* store instructions:
** A sequence of one or more stores writing the bytes of the double word
*** The bytes may be stored in any order.
*** The bytes may be grouped into larger accesses.
*** Any of the bytes may be stored multiple times.

=== Non-idempotent memory handling

An implementation may have a requirement to issue a load/store pair instruction to non-idempotent memory.

If the core implementation does not support Zilsd instructions to non-idempotent memories, the core may use an idempotency PMA to detect it and take a load or store access fault exception in order to avoid unpredictable results.

Software should only use these instructions on non-idempotent memory regions when software can tolerate the required memory accesses being issued repeatedly in the case that they cause exceptions.